### PR TITLE
Move the read_in and write_out subs into the module for code re-use

### PR DESCRIPTION
**Pull request by openstrike**
This change moves the two main input and output subroutines and their dependent private subs from the dpath script into the previously empty App::DPath module. The user-facing functionality of dpath is unchanged as is the test suite which still passes (for my installation at any rate). The benefit here is that any other script or module can now use the App::DPath module to read and write the structures to and from files with all the benefit provided by this dist without having to shell out or otherwise load the dpath script.

The PR isn't entirely finished yet - the POD could be improved and some tests written to access the subs directly instead of only via dpath. I'll be happy to polish it before merging if you were to approve the principle.

This work has been done as part of the [CPAN PR Challenge](http://cpan-prc.org/). The dist was otherwise in great shape and it just seemed to me to be a pity that the module was essentially just a placeholder when some of the subs could be moved there for re-use.

### CODE REVIEW

**Comment by renormalist** [comment]
This patch totally makes sense. Thanks. Tell me when I should merge this PR (because you wrote "not entirely finished yet"). I'm also fine to merge this one right now and subsequent PRs later, too.

**Comment by openstrike** [comment]
Glad you think so. I've started putting some tests together which have uncovered 1 bug already (in what I've done) so it would probably be best to hold off on merging until all the tests are done and pass. Hopefully be there within a week or so.

**Comment by openstrike** [comment]
The tests are now done (see e728636) and the POD is a bit more extensive too. I think it is fine for merging now but if you think anything else needs attention please let me know.

**Comment by openstrike** [comment]
Are you interested in merging this? If so and you let me know I'll resolve the merge conflicts and add the taparchive input type.

**Comment by renormalist** [comment]
Hoppla, I didn't see the update which github says was "1 year ago" - sorry. If you can resolve the conflicts, I will happily merge your work.

**Comment by openstrike** [comment]
The conflicts should be resolved now. Please get back to me if you need anything further to merge this. Thanks.

**Comment by renormalist** [comment]
Finally. Thanks!

**Pull request merged**
